name: edp-gt-open-pr-workflow

on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
        default: ""
      target_branch:
        required: false
        type: string
        default: ""
      callerWorkflowVersion:
        required: false
        type: string
        default: "3.35.0"
    secrets:
      ACTIONS_CONTAINER_DEBUG:
        required: false

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
  ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}

jobs:
  call-prepare-payload:
    uses: TD-Github-Actions/edp-reusable-workflows/.github/workflows/prepare-payload.yml@3.41.2
    with:
      branch: ${{ inputs.branch }}
      target_branch: ${{ inputs.target_branch }}
    secrets:
      ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}

  call-open-pr-workflow:
    needs: call-prepare-payload
    uses: TD-Github-Actions/edp-reusable-workflows/.github/workflows/open-pr-workflow.yml@3.41.2
    with:
      client_payload: ${{ needs.call-prepare-payload.outputs.client_payload }}
    secrets:
      ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}

  terraform-plan:
    needs: call-prepare-payload
    uses: TD-Github-Actions/edp-reusable-workflows/.github/workflows/terraform-plan-workflow.yml@3.41.2
    with:
      client_payload: ${{ needs.call-prepare-payload.outputs.client_payload }}
    secrets:
      ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}
