name: Open PR Workflow Caller
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main
      - release/*
      - develop

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
  ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}

jobs:
  call-edp-gt-open-pr-workflow:
    uses: TD-Github-Actions/edp-reusable-workflows/.github/workflows/edp-gt-open-pr-workflow.yml@EDP-RELEASE-3-N
    with:
      branch: ${{ github.event.pull_request.head.ref }}
      target_branch: ${{ github.event.pull_request.base.ref }}
    secrets:
      ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}
