name: Release Workflow Caller
on:
  workflow_dispatch:
    inputs:
      cycle:
        type: choice
        description: 'RRMINDER: Run the approval Workflow first! EDP Cycle To Run. Only choice is "release-cycle" and it is required.'
        required: true
        options:
          - release-cycle
        default: "release-cycle"
      tag:
        description: 'Git Tag to deploy on the release-cycle'
        required: true
        default: ""
      ci_repo:
        description: 'The repository that builds the artifact to be deployed, if not provided, current repository will be used.'
        required: false
        default: ""
      ci_tag:
        description: 'The version of the artifact to be deployed, if not provided, tag above will be used'
        required: false
        default: ""
      env_path:
        description: 'DP Environment Path Above DEV Classification To Release To'
        required: false
        default: "sit"
      change_order:
        description: 'Applicable EDP Cycles: ["release-cycle"]. Change Order to deploy on the release-cycle. Update Change Order to Implement state before starting release-cycle'
        required: false
        default: ""

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  ACTIONS_STEP_DEBUG: ${{ secrets.ACTIONS_STEP_DEBUG }}
  ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}

jobs:
  call-edp-gt-release-workflow:
    uses: TD-Github-Actions/edp-reusable-workflows/.github/workflows/edp-gt-release-workflow.yml@EDP-RELEASE-3-N
    with:
      cycle: "release-cycle"
      tag: ${{ github.event.inputs.tag || github.event.client_payload.tag }}
      ci_repo: ${{ github.event.inputs.ci_repo || github.event.client_payload.ci_repo }}
      ci_tag: ${{ github.event.inputs.ci_tag || github.event.client_payload.ci_tag }}
      env_path: ${{ github.event.inputs.env_path || github.event.client_payload.env_path }}
      change_order: ${{ github.event.inputs.change_order || github.event.client_payload.change_order }}
    secrets:
      ACTIONS_CONTAINER_DEBUG: ${{ secrets.ACTIONS_CONTAINER_DEBUG }}
